FROM ubuntu:16.04

ENV http_proxy $http_proxy
ENV https_proxy $https_proxy

RUN echo 'deb [trusted=yes] http://download.tizen.org/tools/latest-release/Ubuntu_16.04/ /' | cat >> /etc/apt/sources.list

RUN apt-get update && apt-get --yes --force-yes install gbs

RUN apt-get --yes --force-yes install wget unzip
RUN wget http://download.tizen.org/sdk/tizenstudio/official/binary/sdb_3.1.4_ubuntu-64.zip -O sdb.zip
RUN unzip -d tmp sdb.zip && rm sdb.zip
RUN cp tmp/data/tools/sdb /usr/bin/. && rm -rf tmp 